import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                serif: ['Noto Serif', ...defaultTheme.fontFamily.serif],
                'display-hero': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                'display-hero-mobile': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                'headline-lg': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                'headline-md': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                'body-lg': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                'body-md': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                'label-md': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                'caption-caps': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
            },
            fontSize: {
                'display-hero': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
                'display-hero-mobile': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '800' }],
                'headline-lg': ['30px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '700' }],
                'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
                'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
                'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'label-md': ['14px', { lineHeight: '20px', fontWeight: '600' }],
                'caption-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
            },
            colors: {
                primary: 'var(--color-primary)',
                'on-primary': 'var(--color-on-primary)',
                'primary-container': 'var(--color-primary-container)',
                'on-primary-container': 'var(--color-on-primary-container)',
                'primary-fixed': 'var(--color-primary-fixed)',
                'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
                'on-primary-fixed': 'var(--color-on-primary-fixed)',
                'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
                'primary-50': 'var(--color-primary-50)',
                'primary-100': 'var(--color-primary-100)',
                'primary-200': 'var(--color-primary-200)',
                'primary-300': 'var(--color-primary-300)',
                'primary-400': 'var(--color-primary-400)',
                'primary-500': 'var(--color-primary-500)',
                'primary-600': 'var(--color-primary-600)',
                'primary-700': 'var(--color-primary-700)',
                'primary-800': 'var(--color-primary-800)',
                'primary-900': 'var(--color-primary-900)',
                'primary-950': 'var(--color-primary-950)',

                secondary: 'var(--color-secondary)',
                'on-secondary': 'var(--color-on-secondary)',
                'secondary-container': 'var(--color-secondary-container)',
                'on-secondary-container': 'var(--color-on-secondary-container)',
                'secondary-fixed': 'var(--color-secondary-fixed)',
                'secondary-fixed-dim': 'var(--color-secondary-fixed-dim)',
                'on-secondary-fixed': 'var(--color-on-secondary-fixed)',
                'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',
                'accent-50': 'var(--color-accent-50)',
                'accent-100': 'var(--color-accent-100)',
                'accent-200': 'var(--color-accent-200)',
                'accent-300': 'var(--color-accent-300)',
                'accent-400': 'var(--color-accent-400)',
                'accent-500': 'var(--color-accent-500)',
                'accent-600': 'var(--color-accent-600)',
                'accent-700': 'var(--color-accent-700)',

                tertiary: 'var(--color-tertiary)',
                'on-tertiary': 'var(--color-on-tertiary)',
                'tertiary-container': 'var(--color-tertiary-container)',
                'on-tertiary-container': 'var(--color-on-tertiary-container)',
                'tertiary-fixed': 'var(--color-tertiary-fixed)',
                'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim)',

                background: 'var(--color-background)',
                'on-background': 'var(--color-on-background)',

                surface: 'var(--color-surface)',
                'on-surface': 'var(--color-on-surface)',
                'surface-dim': 'var(--color-surface-dim)',
                'surface-bright': 'var(--color-surface-bright)',
                'surface-container-lowest': 'var(--color-surface-container-lowest)',
                'surface-container-low': 'var(--color-surface-container-low)',
                'surface-container': 'var(--color-surface-container)',
                'surface-container-high': 'var(--color-surface-container-high)',
                'surface-container-highest': 'var(--color-surface-container-highest)',
                'surface-variant': 'var(--color-surface-variant)',
                'on-surface-variant': 'var(--color-on-surface-variant)',

                outline: 'var(--color-outline)',
                'outline-variant': 'var(--color-outline-variant)',

                'status-success': 'var(--color-status-success)',
                'status-warning': 'var(--color-status-warning)',
                'status-danger': 'var(--color-status-danger)',
                'status-info': 'var(--color-status-info)',

                'inverse-surface': 'var(--color-inverse-surface)',
                'inverse-on-surface': 'var(--color-inverse-on-surface)',
                'inverse-primary': 'var(--color-inverse-primary)',
                'surface-tint': 'var(--color-surface-tint)',
                'surface-subtle': 'var(--color-surface-subtle)',
            },
        },
    },

    plugins: [forms],
};
